apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: ci-artifacts
  name: "{{ build_operand_imagestream_name }}"
  namespace: "{{ build_operand_namespace }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ build_operand_imagestream_name }}:latest"
      namespace: "{{ build_operand_namespace }}"
  resources: {}
  source:
    type: Git
    git:
      uri: "{{ build_operand_git_repo }}"
      ref: "{{ build_operand_git_ref }}"
    contextDir: .
  triggers:
  - type: "ConfigChange"
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: "GOLANG_VERSION"
          value: "1.15.8"
        - name: "PLUGIN_VERSION"
          value: "0.9.0"
      dockerfilePath: docker/Dockerfile.ubi8
