---
build_operand_git_repo: "https://gitlab.com/nvidia/kubernetes/gpu-feature-discovery.git"
build_operand_git_ref: "master"
build_operand_namespace: "gpu-operator-resources"
build_operand_imagestream_name: "gfd"
